Repository kubaliski/quiz_app, pull requests merged in 2025-05, with the labels that each got.

#37 Añadir test de MPO de Molpe
  dev-dist/sw.js
  src/data/asignaturas/moduloProfesionalOptativo/index.js
  src/data/asignaturas/moduloProfesionalOptativo/modulos/cientoMolpe.js
Labels: enhancement

#39 Añadir test simulacro del 04/05/2025
  dev-dist/sw.js
  src/data/asignaturas/lenguajeDeMarcas/index.js
  src/data/asignaturas/lenguajeDeMarcas/modulos/simulacromayo.js
Labels: enhancement

#40 Añadir modulo base de datos del primer simulacro de examen
  dev-dist/sw.js
  src/data/asignaturas/basesDeDatos/index.js
  src/data/asignaturas/basesDeDatos/modulos/moduloSimulacroUno.js
Labels: enhancement

#43 Mejora manejo de caché del Service Worker para actualización de módulos
  SECURITY.md
  dev-dist/sw.js
  dev-dist/workbox-523f56e0.js
  package-lock.json
  package.json
  src/App.jsx
  src/components/common/SWErrorHandler.jsx
  src/components/common/ServiceWorkerUpdater.jsx
  src/components/common/index.js
  src/pages/ModulesPage.jsx
  src/services/quizDataService.js
  src/services/swService.js
  vite.config.js
Labels: enhancement

#44 Arreglo de manejo de rutas relativas en produccion
  src/services/quizDataService.js
Labels: bug

#46 Arreglo pregunta 3037
  src/data/asignaturas/sistemasInformaticos/modulos/cienPreguntas.js
Labels: enhancement

#48 refactor:mejorada logica sw
  dev-dist/sw.js
  dev-dist/workbox-84006cf1.js
  generate-version.js
  netlify-postbuild.js
  netlify.toml
  public/version.json
  src/components/common/ServiceWorkerUpdater.jsx
  src/components/layout/Footer.jsx
  src/services/swService.js
  vite.config.js
Labels: enhancement

#49 Arreglo cuelgue SW
  dev-dist/sw.js
  src/components/common/ServiceWorkerUpdater.jsx
  src/services/swService.js
Labels: bug

#50 Añadir módulo Sistemas Informáticos y mejoras de accesibilidad
  SECURITY.md
  dev-dist/sw.js
  eslint.config.js
  package.json
  src/data/asignaturas/sistemasInformaticos/index.js
  src/data/asignaturas/sistemasInformaticos/modulos/cienPreguntas.js
  src/data/asignaturas/sistemasInformaticos/modulos/simulacroUnoSistemas.js
  src/pages/QuizPage.jsx
  src/services/quizDataService.js
Labels: bug, enhancement

#52 Arreglo Pregutna 5001 Entornos
  public/version.json
  src/data/asignaturas/entornosDeDesarrollo/modulos/pruebasSoftware.js
Labels: bug

#53 Mejora del sistema de detección de versiones en producción
  generate-version.js
  netlify-postbuild.js
  netlify.toml
  package.json
  src/components/common/ServiceWorkerUpdater.jsx
  src/services/swService.js
  verify-version.js
Labels: bug

#54 Añadir modulos tema 1 al 4 de ITP
  SECURITY.md
  dev-dist/sw.js
  package.json
  public/version.json
  src/components/layout/Footer.jsx
  src/data/asignaturas/itinerarioParaLaEmpleabilidad/index.js
  src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/unidadCuatro.js
  src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/unidadDos.js
  src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/unidadTres.js
  src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/unidadUno.js
Labels: enhancement

#55 fix: respuesta duplicada corregida
  src/data/asignaturas/sistemasInformaticos/modulos/simulacroUnoSistemas.js
Labels: bug

#56 Añadir los Test de Tercer Trimestre de MPO
  SECURITY.md
  dev-dist/sw.js
  package.json
  public/images/mpo/tercerTrimestre.png
  src/components/layout/Footer.jsx
  src/data/asignaturas/moduloProfesionalOptativo/index.js
  src/data/asignaturas/moduloProfesionalOptativo/modulos/tercerTrimestreDos.js
  src/data/asignaturas/moduloProfesionalOptativo/modulos/tercerTrimestreUno.js
Labels: enhancement

#59 [BUG] Tamaño de texto adaptativo en opciones de quiz para dispositivos móviles
  dev-dist/sw.js
  src/components/quiz/QuestionCard.jsx
  src/components/quiz/QuestionReview.jsx
  src/styles/index.css
Labels: bug

#60 chore: update dependencies
  dev-dist/sw.js
  package-lock.json
Labels: enhancement

#62 Refactorización de QuizPage y solución a pérdida de progreso durante actualizaciones de PWA
  SECURITY.md
  dev-dist/sw.js
  package.json
  src/components/common/Dialog.jsx
  src/components/common/Modal.jsx
  src/components/common/ServiceWorkerUpdater.jsx
  src/components/layout/Footer.jsx
  src/components/quiz/PendingQuizzes.jsx
  src/components/quiz/QuizContent.jsx
  src/components/quiz/QuizDialogs.jsx
  src/components/quiz/QuizHeader.jsx
  src/components/quiz/QuizProgress.jsx
  src/components/quiz/index.js
  src/context/QuizContext.jsx
  src/context/QuizProvider.jsx
  src/context/index.js
  src/hooks/index.js
  src/hooks/useQuizContext.js
  src/hooks/useQuizDialog.js
  src/hooks/useQuizLoader.js
  src/hooks/useQuizNavigation.js
  src/hooks/useQuizProgress.js
  src/pages/HomePage.jsx
  src/pages/QuizPage.jsx
  src/pages/ResultsPage.jsx
  src/services/quizDataService.js
  src/styles/index.css
  src/tests/unit/pages/QuizPage.test.jsx
  src/utils/quizConstants.js
  src/utils/quizUtils.js
Labels: bug, enhancement

#69 Añadir Simulacro 2 de Bases de datos
  SECURITY.md
  dev-dist/sw.js
  package.json
  src/data/asignaturas/basesDeDatos/index.js
  src/data/asignaturas/basesDeDatos/modulos/moduloSimulacroDos.js
  src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/importanteExamen.js
  src/data/asignaturas/moduloProfesionalOptativo/modulos/simulacroUnoMPO.js
Labels: enhancement

#71 Feat/unidades 5 6 itp
  dev-dist/sw.js
  src/data/asignaturas/itinerarioParaLaEmpleabilidad/index.js
  src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/unidadCinco.js
  src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/unidadSeis.js
Labels: enhancement

#75 [BUGFIX] Corrección de ID duplicado en módulo importanteExamen02
  dev-dist/sw.js
  src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/importanteExamen02.js
Labels: bug

#78 [BUG]: Arreglo comportamiento menú movil
  src/components/layout/Header.jsx
  src/components/layout/MobileMenu.jsx
  src/data/asignaturas/entornosDeDesarrollo/modulos/simulacroEntornosDos.js
Labels: bug

#79 Añadir Simulacro 2 de Sistemas y Simulacro de primer bloque de Programación
  SECURITY.md
  dev-dist/sw.js
  package.json
  src/data/asignaturas/programacion/index.js
  src/data/asignaturas/programacion/modulos/simBloqueUno.js
  src/data/asignaturas/sistemasInformaticos/index.js
  src/data/asignaturas/sistemasInformaticos/modulos/simulacroDosSistemas.js
Labels: enhancement

#80 Añadir Simulacros de examen de programación bloques 2 al 4
  dev-dist/sw.js
  src/data/asignaturas/programacion/index.js
  src/data/asignaturas/programacion/modulos/diezAbril.js
  src/data/asignaturas/programacion/modulos/simBloqueCuatro.js
  src/data/asignaturas/programacion/modulos/simBloqueDos.js
  src/data/asignaturas/programacion/modulos/simBloqueTres.js
  src/data/asignaturas/programacion/modulos/simBloqueUno.js
Labels: enhancement

#81 feat(importanteExamen02.js): Añadidas preguntas del tema 5
  SECURITY.md
  package.json
  src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/importanteExamen02.js
Labels: enhancement

#82 Deseleccionar preguntas
  src/components/quiz/QuestionCard.jsx
Labels: enhancement

#84 Añadir el simulacro 2 de Raúl Programación VL
  dev-dist/sw.js
  src/data/asignaturas/programacion/index.js
  src/data/asignaturas/programacion/modulos/simulacroVirtualLab.js
Labels: enhancement

#88 [BUG] Tiempo de toast se reinicia al crear nuevos
  dev-dist/sw.js
  src/components/common/Toast.jsx
  src/components/common/ToastContainer.jsx
Labels: bug

#89 Añadir Modulos Lenguaje De Marco , Bases de Datos e ITP
  SECURITY.md
  dev-dist/sw.js
  package.json
  src/data/asignaturas/basesDeDatos/index.js
  src/data/asignaturas/basesDeDatos/modulos/moduloSimulacroTres.js
  src/data/asignaturas/itinerarioParaLaEmpleabilidad/index.js
  src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/unidadOcho.js
  src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/unidadSiete.js
  src/data/asignaturas/lenguajeDeMarcas/index.js
  src/data/asignaturas/lenguajeDeMarcas/modulos/simulacroTresLenguajeDeMarcas.js
  src/data/asignaturas/programacion/index.js
  src/data/asignaturas/programacion/modulos/simBloqueSeis.js
  src/pages/QuizPage.jsx
  src/utils/toastUtils.js
Labels: enhancement

#90 [BUG] Corregido error al cargar módulos de preguntas favoritas
  dev-dist/sw.js
  src/components/quiz/FavoritesQuizLoader.jsx
  src/hooks/quiz/useQuizLoader.js
  src/pages/QuizPage.jsx
Labels: bug

#94 Arreglos respuestas de colecciones ximo
  src/data/asignaturas/programacion/modulos/simBloqueSeis.js
Labels: bug

#99 Añadir Sistema de descarga de preguntas en PDF
  SECURITY.md
  dev-dist/sw.js
  package-lock.json
  package.json
  src/components/quiz/FavoriteQuizzes.jsx
  src/components/quiz/PDFGenerator.jsx
  src/components/quiz/PendingQuizzes.jsx
  src/components/quiz/index.js
  src/context/QuizProvider.jsx
  src/hooks/quiz/useQuizDialog.js
  src/hooks/quiz/useQuizLoader.js
  src/hooks/quiz/useQuizProgress.js
  src/pages/QuizPage.jsx
  src/pages/ResultsPage.jsx
Labels: bug, enhancement

#100 Corrección de bloqueo de DOM/scroll y reorganización de componentes
  dev-dist/sw.js
  src/components/common/buttons/Button.jsx
  src/components/common/buttons/FavoriteButton.jsx
  src/components/common/cards/Card.jsx
  src/components/common/code/CodeBlock.jsx
  src/components/common/dialogs/Dialog.jsx
  src/components/common/dialogs/Modal.jsx
  src/components/common/errors/DOMRecoveryMonitor.jsx
  src/components/common/errors/GlobalErrorBoundary.jsx
  src/components/common/errors/SWErrorHandler.jsx
  src/components/common/feedback/ErrorMessage.jsx
  src/components/common/feedback/LoadingSpinner.jsx
  src/components/common/feedback/ProgressBar.jsx
  src/components/common/feedback/Toast.jsx
  src/components/common/feedback/ToastContainer.jsx
  src/components/common/index.js
  src/components/common/sw/ServiceWorkerUpdater.jsx
  src/components/layout/Footer.jsx
  src/components/layout/Header.jsx
  src/components/layout/LayoutWithSidebar.jsx
  src/components/layout/MobileMenu.jsx
  src/components/layout/common/BrandLogo.jsx
  src/components/layout/common/PageHeader.jsx
  src/components/layout/containers/Layout.jsx
  src/components/layout/footer/Footer.jsx
  src/components/layout/footer/FooterNav.jsx
  src/components/layout/footer/VersionInfo.jsx
  src/components/layout/header/DesktopControls.jsx
  src/components/layout/header/DesktopNav.jsx
  src/components/layout/header/Header.jsx
  src/components/layout/header/MobileMenu.jsx
  src/components/layout/header/ThemeToggle.jsx
  src/components/layout/index.js
  src/components/layout/notifications/PWAInstallPrompt.jsx
  src/components/quiz/export/PDFGenerator.jsx
  src/components/quiz/favorites/FavoriteButton.jsx
  src/components/quiz/favorites/FavoriteQuizzes.jsx
  src/components/quiz/favorites/FavoritesQuizLoader.jsx
  src/components/quiz/index.js
  src/components/quiz/media/ImageResource.jsx
  src/components/quiz/navigation/QuestionNavigator.jsx
  src/components/quiz/navigation/QuizNavigation.jsx
  src/components/quiz/pending/PendingQuizzes.jsx
  src/components/quiz/progress/QuizProgress.jsx
  src/components/quiz/progress/ResultSummary.jsx
  src/components/quiz/questions/QuestionCard.jsx
  src/components/quiz/questions/QuestionReview.jsx
  src/components/quiz/selectors/ModuleSelector.jsx
  src/components/quiz/selectors/SubjectSelector.jsx
  src/components/quiz/session/QuizContent.jsx
  src/components/quiz/session/QuizDialogs.jsx
  src/components/quiz/session/QuizHeader.jsx
  src/hooks/core/useScrollDirection.js
  src/hooks/quiz/useQuizLoader.js
  src/hooks/quiz/useQuizProgress.js
  src/main.jsx
  src/pages/HomePage.jsx
  src/pages/ResultsPage.jsx
  src/services/errorService.js
Labels: bug

#101 Añadir Test de Repaso ITP faltantes
  SECURITY.md
  dev-dist/sw.js
  package.json
  src/components/quiz/favorites/FavoriteButton.jsx
  src/data/asignaturas/itinerarioParaLaEmpleabilidad/index.js
  src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/legislacionYPrevencion.js
  src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/repasoUnidadCuatro.js
  src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/repasoUnidadDos.js
  src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/repasoUnidadTres.js
  src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/repasoUnidadUno.js
  src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/unidadCinco.js
  src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/unidadCuatro.js
  src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/unidadDos.js
  src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/unidadOcho.js
  src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/unidadSeis.js
  src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/unidadSiete.js
  src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/unidadTres.js
  src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/unidadUno.js
Labels: enhancement

#105 feat:anadir bloques 9 10 a programacion
  dev-dist/sw.js
  src/data/asignaturas/programacion/index.js
  src/data/asignaturas/programacion/modulos/simBloqueDiez.js
  src/data/asignaturas/programacion/modulos/simBloqueNueve.js
  src/data/asignaturas/programacion/modulos/simulacroVirtualLabDos.js
Labels: enhancement

#106 Añadir
  dev-dist/sw.js
  src/data/asignaturas/itinerarioParaLaEmpleabilidad/index.js
  src/data/asignaturas/moduloProfesionalOptativo/modulos/tercerTrimestreUno.js
  src/data/asignaturas/programacion/index.js
  src/data/asignaturas/programacion/modulos/examenDAM.js
Labels: enhancement

#107 Error respuesta de pregunta 31806
  src/data/asignaturas/programacion/modulos/examenDAM.js
Labels: bug

#108 Añadir simulacros 3 y 4 de Sistemas informáticos
  SECURITY.md
  dev-dist/sw.js
  package.json
  src/data/asignaturas/sistemasInformaticos/index.js
  src/data/asignaturas/sistemasInformaticos/modulos/simulacroCuatroSistemas.js
  src/data/asignaturas/sistemasInformaticos/modulos/simulacroTresSistemas.js
Labels: enhancement

#109 Error modulo Id en el modulo Bloque tres preguntas importantes ITP
  dev-dist/sw.js
  src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/importanteExamen03.js
Labels: bug

#111 Añadir Examen lenguaje de marcas
  dev-dist/sw.js
  src/data/asignaturas/lenguajeDeMarcas/index.js
  src/data/asignaturas/lenguajeDeMarcas/modulos/examenLenguaje.js
Labels: enhancement
